name: driver
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.6
  firebase_auth: ^1.3.0
  firebase_core: ^1.2.1
  animated_splash_screen: ^1.1.0
  flutter_native_splash: ^2.0.2
  font_awesome_flutter: ^9.0.0
  google_sign_in: ^5.0.3
  google_fonts: ^2.1.0
  image_picker_gallery_camera: ^0.2.2
  images_picker: ^1.2.4
  google_maps_flutter: ^2.0.11
  location: ^4.3.0
  get: ^4.6.1
  geolocator: ^8.0.1
  http: ^0.13.3
  provider: ^5.0.0
  firebase_database: ^7.1.1
  firebase_storage:
  cached_network_image: ^3.0.0
  dio: ^4.0.0
  file_picker: ^3.0.3
  introduction_screen: ^2.1.0
  permission_handler: ^8.3.0
  open_settings: ^2.0.2
  open_apps_settings: ^0.0.3
  location_permissions: ^4.0.0
  line_icons: ^2.0.1
  cloud_firestore: ^2.5.3
  geoflutterfire: ^3.0.1
  cloud_firestore_web: ^2.5.0
  supabase: ^0.2.10
  flutter_local_notifications: ^9.1.2
  firebase_messaging: ^11.1.0
  firebase_messaging_web: ^2.2.5
  circular_profile_avatar: ^2.0.5
  avatar_glow: ^2.0.2
  slide_to_act: ^2.0.1
  iconsax: ^0.0.8
  get_storage: ^2.0.3
  loader_overlay: ^2.0.4+3
  url_launcher: ^6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter_native_splash:
  color: "#000000"
  image: "asset/images/logo.png"

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/images/
    - asset/Animation/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Ubuntu
      fonts:
        - asset: fonts/Ubuntu-Medium.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Medium.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
